import os

NOTA_MINIMA = 0
NOTA_MAXIMA = 100
RANKING_MINIMO = 1
POPULARIDADE_MINIMA = 0
CAPITULOS_MINIMO = 0

NOTA_BAIXA_LIMITE = 60
NOTA_INTERMEDIARIA_LIMITE = 80

RANKING_DESTAQUE_ALTO = 50
RANKING_DESTAQUE_INTERMEDIARIO = 150

DIRETORIO_ATUAL = os.path.dirname(os.path.abspath(__file__))
ARQUIVO_CSV = os.path.join(DIRETORIO_ATUAL, "dados.csv")
SEPARADOR = ";"
